export const BATCH_DO_NOT_DISTURB_INITIAL_STATE = false;
export const BATCH_DEFAULT_OPT_OUT_INITIAL_STATE = false;
export const BATCH_DEFAULT_PROFILE_CUSTOM_ID_MIGRATION = true;
export const BATCH_DEFAULT_PROFILE_CUSTOM_DATA_MIGRATION = true;
